name: mdh
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - numpy=1.22.*
  - pandas=1.4.*
  - matplotlib=3.5.*
  - scikit-learn=1.0.*
  - notebook=6.4.*
  - tqdm=4.64.*
  - ase=3.22.*
  - networkx=2.8
  - seaborn=0.11.*
  - cmcrameri=1.4
