name: elf
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - ase=3.22.*
  - cmcrameri=1.5
  - ipywidgets=8.0.*
  - joblib=1.2.*
  - matplotlib=3.7.*
  - networkx=3.1.*
  - notebook=6.5.*
  - numpy=1.24.*
  - pandas=2.0.*
  - scikit-learn=1.2.*
  - scipy=1.10.*
  - tqdm=4.65.*
